config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "static_pages#home"

  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      patch 'update-avatar'
      patch 'update-password'
      patch 'update-profile'
    end
  end

  post '/cart/create_order', to: 'cart#create_order', as: 'create_order'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  get 'checkouts/success', to: 'checkouts#success'
  get 'orders/index'

  resources :games, only: [:show]
  resources :genres, only: [:show]
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence:  true, uniqueness: true
  has_many :game_genres
  has_many :games, through: :game_genres

  def self.ransackable_associations(auth_object = nil)
    ["games"]
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[created_at id id_value name updated_at]
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  skip_before_action :authenticate_user!, only: [:show]

  def show
    @genre = Genre.find(params[:id])

    @games = @genre.games.page(params[:page]).per(14)

  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_genre.html.erb
<div class="container">
  <p><strong>Genre Name:</strong> <%= @genre.name %></p>

  <div class="row">
    <% @games.each do |game| %>
      <div class="col-md-4 text-center">
        <%= render partial: "games/game", locals: { game: game } %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-12 text-center">
      <div class="pagination">
        <%= paginate @games %>
      </div>
    </div>
  </div>
</div>

app/views/genres/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Genres</h1>

<div id="genres">
  <% @genres.each do |genre| %>
    <%= render genre %>
    <p>
      <%= link_to "Show this genre", genre %>
    </p>
  <% end %>
</div>

app/views/genres/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @genre %>

<div>
  <%#= link_to "Back to genres", genres_path %>
</div>