config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "static_pages#home"

  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      patch 'update-avatar'
      patch 'update-password'
      patch 'update-profile'
    end
  end

  post '/cart/create_order', to: 'cart#create_order', as: 'create_order'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  get 'checkouts/success', to: 'checkouts#success'
  get 'orders/index'

  resources :games, only: [:show]
  resources :genres, only: [:show]
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables, dependent: :delete_all
  has_many :games, through: :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @game = Game.find_by(id: params[:id])
    quantity = params[:quantity].to_i

    if @game.remaining_keys >= quantity
      current_orderable = @cart.orderables.find_by(game_id: @game.id)

      if current_orderable && quantity > 0
        current_orderable.update(quantity: current_orderable.quantity = quantity)
      elsif quantity <= 0
        current_orderable.destroy
      else
        @cart.orderables.create(game: @game, quantity:)
      end

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [turbo_stream.replace('cart',
                                                     partial: 'cart/cart',
                                                     locals: { cart: @cart }),
                                turbo_stream.replace(@game),
                                turbo_stream.replace('cart-link', partial: 'cart/cart_link')]
        end
      end
    else
      flash[:error] = "Sorry but amount you want to buy exceeds available in stock"
      redirect_to cart_path, data: {turbo: false}
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart',
                                                   partial: 'cart/cart',
                                                   locals: { cart: @cart }),
                              turbo_stream.replace('cart-link', partial: 'cart/cart_link')]
      end
    end
  end

  def create_order
    unless @cart.orderables.empty?

      current_user.set_payment_processor :stripe
      current_user.payment_processor.customer

      total_amount = (@cart.total * 100).to_i # Stripe expects amount in cents

      @checkout_session = @checkout_session = current_user
                                                .payment_processor
                                                .checkout(
                                                  mode: 'payment',
                                                  line_items: [
                                                    {
                                                     price_data:
                                                       {
                                                       currency: 'usd',
                                                       unit_amount: total_amount,
                                                       product_data:
                                                         { name: 'Game Shop Cart Payment'}
                                                       },
                                                     quantity: 1
                                                     }],
                                                  success_url: checkouts_success_url,
                                                )

      session[:order_data] = {
        user_id: current_user.id,
        orderables: @cart.orderables.map { |orderable| {game_id: orderable.game_id, quantity: orderable.quantity, price: orderable.game.price_for_one} },
        total_price: @cart.total
      }
      @cart.orderables.destroy_all

      redirect_to @checkout_session.url, allow_other_host: true
    else
      flash[:error] = "Cart is Empty"
      redirect_to root_path
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <% if flash[:error].present? %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="alert alert-danger" role="alert">
            <%= flash[:error] %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <h1 class="card-title">Cart</h1>
            <% if @cart.orderables.count > 0 %>
              <%= render "cart/orderable" %>
              <p class="card-text"><b>Total:</b> <%= @cart.total %></p>
            <% else %>
              <p class="card-text">Your cart is empty</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/cart/_cart_link.erb
<%= turbo_frame_tag 'cart-link' do %>
  <%= link_to cart_path, data: { turbo: false }, class: 'nav-link position-relative' do %>
    <i class="fa-solid fa-cart-shopping fa-xl"></i>
    <span class="badge badge-danger position-absolute top-0 start-100 translate-middle"><%= @cart.orderables.count %></span>
  <% end %>
<% end %>

app/views/cart/_orderable.html.erb
<% @cart.orderables.each do |orderable| %>
  <% game = orderable.game %>
  <div class="row-md-4 mb-3 game-row"> <!-- Adjust the column size based on your layout -->
    <div class="card">
      <div class="row no-gutters">
        <div class="col-md-4">
          <%= image_tag(game.cover_image(200, 200), class: "card-img") %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><b>Name:</b> <%= game.name %></h5>
            <p class="card-text"><%= game.developer %></p>
            <p class="card-text"><%= game.price_for_one %></p>
            <div class="cart-buttons">
              <div class="cart-update">
                <%= form_with(url: cart_add_path) do |f| %>
                  <%= f.hidden_field :id, value: game.id %>
                  <%= f.number_field :quantity, value: orderable.quantity, min: 0, class: "mb-10" %>
                  <%= f.submit "Update", class: "btn btn-primary btn-block mb-2" %>
                <% end %>
              </div>
              <div class="cart-delete">
                <%= form_with(url: cart_remove_path) do |f| %>
                  <%= f.hidden_field :id, value: orderable.id %>
                  <%= f.submit "X", class: "btn btn-danger btn-block" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/cart/show.html.erb
<div>
 <%= render partial: "cart" %>
  <div class="checkout-button">
    <%= button_to 'Checkout', create_order_path, method: :post, class: 'btn btn-primary', data: { turbo: false } %>
  </div>
</div>