config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "static_pages#home"

  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      patch 'update-avatar'
      patch 'update-password'
      patch 'update-profile'
    end
  end

  post '/cart/create_order', to: 'cart#create_order', as: 'create_order'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  get 'checkouts/success', to: 'checkouts#success'
  get 'orders/index'

  resources :games, only: [:show]
  resources :genres, only: [:show]
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items

  has_many :orderables
  has_many :carts, through: :orderables

  has_one_attached :cover
  has_many_attached :pictures

  #validates :genre_ids, presence: true
  validates :name, presence: true, uniqueness: true
  validates :price_for_one, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1000.0 }

  has_many :game_genres, dependent: :delete_all
  has_many :genres, through: :game_genres

  has_many :game_keys

  # Define which associations are searchable
  def self.ransackable_associations(auth_object = nil)
    %w[genres cover]
  end
  #
  def self.ransackable_attributes(auth_object = nil)
    %w[name platforms genre distributor developer]
  end

  def cover_image(width, height)
    if cover.attached?
      cover.variant(format: :png, resize_to_fill: [width, height]).processed
    else
      ""
    end
  end

  def pictures_thumbnails(width, height)
    if pictures.attached?
      pictures.map do |picture|
        picture.variant(format: :png, resize_to_fill: [width, height]).processed
      end
    else
      []
    end
  end

  def remaining_keys
    game_keys.count
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  def show
    @game = Game.find(params[:id])
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_game.erb
<div id="<%= dom_id game %>">
  <div class="row">
    <div class="col-md-4 game-cover">
      <%= link_to game_path(game) do %>
        <%= image_tag(game.cover_image(350, 350), class: "img-fluid rounded") %>
      <% end %>
    </div>
  </div>
  <h4 class="mt-2"><%= game.name %></h4>
  <p>Genres:
    <% game.genres.each do |genre| %>
      <%= link_to genre.name, genre %>
      <% unless genre == game.genres.last %>,
      <% end %>
    <% end %>
  </p>

  <% if game.remaining_keys > 0 %>
    <%= form_with(url: cart_add_path) do |f| %>
      <%= f.hidden_field :id, value: game.id %>
      <%= f.hidden_field :quantity, value: 1 %>
      <%= f.submit "Add to Cart" %>
    <% end %>
  <% else %>
    Out of Stock
  <% end %>
</div>

app/views/games/show.erb
<div class="col-md-8 game-details">

  <div class="row">
    <div class="col-md-4 game-cover">
      <%= image_tag(@game.cover_image(350, 350), class: "img-fluid rounded") %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h2><%= @game.name %></h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <p><strong>Genre:</strong> <%= @game.genre %></p>
      <p><strong>Developer:</strong> <%= @game.developer %></p>
      <p><strong>Distributor:</strong> <%= @game.distributor %></p>
      <p><strong>Platforms:</strong> <%= @game.platforms %></p>
    </div>
    <div class="col-md-6">
      <p><strong>Description:</strong> <%= @game.description %></p>
      <p><strong>Price:</strong> <%= @game.price_for_one %>$</p>
      <p><strong>Amount available:</strong> <%= @game.remaining_keys %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h3>Game Pictures</h3>
    </div>
  </div>


  <div class="row">
    <div class="col-md-12">
      <div class="game-pictures">
        <% @game.pictures_thumbnails(350, 350).each do |picture| %>
          <%= image_tag(picture, class: "img-fluid rounded mr-2 mb-2") %>
        <% end %>
      </div>
    </div>
  </div>
</div>