config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "static_pages#home"

  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      patch 'update-avatar'
      patch 'update-password'
      patch 'update-profile'
    end
  end

  post '/cart/create_order', to: 'cart#create_order', as: 'create_order'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  get 'checkouts/success', to: 'checkouts#success'
  get 'orders/index'

  resources :games, only: [:show]
  resources :genres, only: [:show]
end

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'Home page', root_path, id: "logo" %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= render partial: "cart/cart_link" %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to user_path(current_user) do %>
                  Profile <i class="fa-regular fa-user"></i>
                <% end %>
              </li>
              <li>
                <%= link_to orders_index_path(user_id: current_user.id) do %>
                  My Orders <i class="fa-solid fa-cart-arrow-down"></i>
                <% end %>
              </li>
              <li class="divider"></li>
              <li class="logout-li">
                <%= button_to "Log out", destroy_user_session_path,method: :delete, data: { turbo: false } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path, data: { turbo: false } %></li>
          <li><%= link_to "Admin Panel", new_admin_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameShop</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render 'layouts/header' %>
  <% flash.each do |type, msg| %>
  <%= content_tag :div, msg, class: build_alert_classes(type) %>
<% end %>
  <%= yield %>
</body>
</html>